### PR TITLE
celery-haystack integration

### PR DESCRIPTION
**Pull request by sdreher**
configuration for django-transaction-hooks and celery-haystack

### CODE REVIEW

**Comment by thraxil** [comment]
Thought: Did you happen to whitelist ceramic (45.79.184.118) for Solr access already? That's where the celery worker will be running.

**Comment by sdreher** [comment]
Nope. Thanks for the reminder.

**Comment by thraxil** [comment]
Cool. I'll hold off on this until we get confirmation of the whitelist.

**Comment by sdreher** [comment]
@thraxil - ceramic has been whitelisted on staging. I've been asked to verify interaction there before the whitelist change will be made to production. I've just removed footprints from CI for a moment. Can you do this pull request to deliver the code to staging to allow a quick functionality test?

**Pull request merged**
