### PR TITLE
Written Work detail page: implement intrapage history

### PR DESCRIPTION
**Pull request by sdreher**
Use pushState/popState to record and playback navigation to Imprint/BookCopy/Footprint.

### CODE REVIEW

**Comment by nikolas** [comment]
I'm seeing some broken behavior with this change:
* On a WrittenWork page,
* Click on "Book Copy"
* The URL path changes to something like `/writtenwork/1/296/324/`, which, if you refresh the page, isn't a valid URL. That's notable because if you then click "full details" on one of the items, then click 'back', you get a 404. That doesn't happen currently on master.. so maybe we should fix it up. Testing on Chrome/Linux.

**Comment by nikolas** [comment]
Maybe all we need to do is update the regex for the writtenwork path to allow for and ignore the subsidiary IDs.

**Comment by sdreher** [comment]
Processing for the extended url is finished, and will come in the next PR.

**Comment by nikolas** [comment]
Cool looks good

**Pull request merged**
